version: "3.9"

services:

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: api-local
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-local:5432/reservas_local
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: local_jwt_secret_dev
      SERVER_PORT: 8080
    depends_on:
      postgres-local:
        condition: service_healthy
    networks:
      - local-network

  postgres-local:
    image: postgres:15-alpine
    container_name: postgres-local
    environment:
      POSTGRES_DB: reservas_local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata-local:/var/lib/postgresql/data
      - ../docs/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reservas_local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local-network

volumes:
  pgdata-local:

networks:
  local-network:
    driver: bridge
