name: Deploy – Prod
on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven
        # Em vez de 'working-directory', entramos na pasta manualmente no script
        run: |
          echo "Buscando o pom.xml do backend..."
          cd backend/reservas-system || cd reservas-system/backend/reservas-system
          
          echo "Pasta atual: $(pwd)"
          ls -la
          
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push imagem Prod
        run: |
          # Navega até onde está o Dockerfile
          cd backend || cd reservas-system/backend
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod
            cd ~/reservas-system
            docker compose -f infra/docker-compose.yml up -d --no-deps api-prod
            docker image prune -f
