name: Deploy â€“ Prod
on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Removido o cache para evitar o erro de 'No file matched' que trava o build
          
      - name: Build Maven
        working-directory: backend/reservas-system
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push imagem Prod
        working-directory: backend
        run: |
          # O contexto do Docker continua sendo /backend para achar o Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod
            cd ~/reservas-system
            docker compose -f infra/docker-compose.yml up -d --no-deps api-prod
            docker image prune -f
