name: Deploy – Prod
on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Localizar e Preparar Maven
        run: |
          # Busca o arquivo mvnw em qualquer lugar do repositório e entra na pasta dele
          MVNW_PATH=$(find . -name "mvnw" -not -path "*/target/*" | head -n 1)
          MVNW_DIR=$(dirname "$MVNW_PATH")
          echo "Diretório encontrado: $MVNW_DIR"
          
          chmod +x "$MVNW_PATH"
          cd "$MVNW_DIR" && ./mvnw clean package -DskipTests

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push imagem Prod
        # Mantemos 'backend' como base para o Dockerfile
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reservas-api:prod
            cd ~/reservas-system
            docker compose -f infra/docker-compose.yml up -d --no-deps api-prod
            docker image prune -f
